version: '2'

services:
  app:
    image: 'ofin:latest'
    build:
      context: .
    container_name: ofin-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ofin
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
     - 8049:8049     
  db:
    image: 'postgres:13.1-alpine'
    container_name: ofin-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

